### ISSUE TITLE
Error on 'deprecated API' are showing when running with the overlay

### ISSUE THREAD

**Issue by MCM-TimT** [ubilabs/threejs-overlay-view#20]
**Describe the bug**
Whenever running with the ubilabs/threejs-overlay-view, I am getting several of the following messages in the browser console output:
`This API has been deprecated, and will be going away by March 15th, 2022. Please migrate to the new API with the signature fromLatLngAltitude(latLngAltitude, rotations, scale).`

The issue is not only occurring on my own project, but also when running the examples on your webpage.

**To Reproduce**
Run any of the four examples on the website, for example: [cube example](https://ubilabs.github.io/threejs-overlay-view/cube.html) with console open in the browser.

**Expected behavior**
I'm expecting no deprecation errors to occur.

**Screenshots**
![Deprecated error threejs view](https://user-images.githubusercontent.com/65541832/154518570-0e2e3ba5-da2d-4a08-b2c8-7cf5c2492efa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 98.0.1108.50

**Comment by mudasirhamid** [comment]
I am facing same issue

**Comment by mudasirhamid** [comment]
@MCM-TimT 
I have fixed this issue by applying a few changes 
in file : threejs-overlay-view.ts
I changed this 
`transformer.fromLatLngAltitude({lat, lng} ,altitude)`
to 
`transformer.fromLatLngAltitude({lat, lng ,altitude})`


and in node_modules\@types\google.maps\index.d.ts
i just added this google.maps.LatLngAltitudeLiteral instead of google.maps.LatLngLiteral
```
interface CoordinateTransformer {
    fromLatLngAltitude(
        latLngAltitude: google.maps.LatLng | google.maps.LatLngAltitudeLiteral,
        rotations?: Float32Array, scale?: Float32Array): Float64Array;
    getCameraParams(): google.maps.CameraParams;
  }
```
